### PR TITLE
Better Lab Mode

### PR DESCRIPTION
**Pull request by JorenC**
Hi @zond , could you take a look at this when you have time? It needs quite some work, I think.
There is no rush, and it's far from perfect, but it's at least a bit less "primitive" than the version you made. 

There are still many changes to be done. Main things can be found under the "TODO": 
- Make the edit/play as switch functional
- Hide the "play as" selector (disappear) when set to edit
- Make the forward button resolve the phase.

In the TODO's there's also a question on the "hypothetical" vs "historical" phases (e.g. I go back to 1901, change something and commit - there is a "hypothetical 1902" now, but I think that needs to be further discussion, that we need in general. on this. 

I think ideally we would REMOVE the phases from the lab mode currently - you select a phase, turn on lab mode, and lab mode pushes NEW phases - so you can't go back more than the phase you originally opened lab mode with...

Let's discuss in the future.

### CODE REVIEW

**Comment by zond** [comment]
> In the TODO's there's also a question on the "hypothetical" vs "historical" phases (e.g. I go back to 1901, change something and commit - there is a "hypothetical 1902" now, but I think that needs to be further discussion, that we need in general. on this.

I think it's logical that while you are in sandbox mode, you can change everything and build new phases as you wish.

> I think ideally we would REMOVE the phases from the lab mode currently - you select a phase, turn on lab mode, and lab mode pushes NEW phases - so you can't go back more than the phase you originally opened lab mode with...

Why? Let the players play around with whatever they want - it's no difference to the game.

The lab mode we have currently allows you to edit any phase in any way, and when you resolve it creates a new phase. It's the playground I always wanted :D

**Comment by JorenC** [comment]
Hi Martin,

I don't disagree with the functionality, but I think it would be good to _display_ hypothetical turns different from actual turns.
The example of 1901/1902 - if I change 1901 and commit, it will _overwrite_ the actual 1902. That's fine, but what happens with 1903? Is it an existing one? Or a hypothetical one? What happens if I jump to 1903 and then jump back to 1902 - will it load the _actual_ one or the _hypothetical_ one? And how do I know?

My original thinking was to change the text colour for hypothetical turns, so that let's say I move to 1901 and press commit, that turn will become e.g. red. When I go back to that turn, I know it's not the actual turn I'm looking at.


_Why? Let the players play around with whatever they want - it's no difference to the game._
Here it's also to create a starting point, and clear differentiation between Sandbox mode and non-sandbox mode. It would be "weird" if there are 20 England units on the map in 1901, and then 1901 loses it's significance, if you change it. However, if it becomes "fall 1", and you go from there, it makes more sense. However, this one I'm not really strongly opinionated about - more about the one above.

**Comment by JorenC** [comment]
Another reason is to see whether we can remove a game from it's sandbox - now I'm sharing a "sandbox" to a friend, and when they close a game, it jumps to the latest stage of that game - which might mean that they will see turns that panned out differently, get notified of chats etc. 

By separating them, you can distinguish between a GAME and a SANDBOX, and the only thing of "Sandbox mode" is that it copies the current turn into a new sandbox (but they are separate)

**Comment by zond** [comment]
Did you just release this directly to prod? What about our beta? ;)

**Pull request merged**
