### PR TITLE
Convert to regular react app

### PR DESCRIPTION
**Pull request by johnpooch**
Converts existing project to a regular react app.

Follow the instructions in `web-app/README.md` to bring up a dev copy.

There are still a good few steps to do before this is in any way ready for production but just sharing now for early thoughts and feedback.

To do:
- [x] Fix all console warnings and errors
- [ ] Fix styling regressions
- [ ] Thoroughly test all pages for correctness
- [ ] Update top-level README
- [ ] Add deploy workflow (also workout where we're going to deploy to!)

Some other notes:
* The start up time for the app is quite long. This is mainly because of `@material-ui/core` and `@material-ui/icons`. This can be fixed using tree shaking. I've already opened an issue for this: https://github.com/zond/dipact/issues/230
* One of the only actual changes to the component code is that I've replaced the use of `helpers.createIcon` with the more conventional way of using `@material-ui/icons`. I was struggling to get it to work properly the way it was before and using the conventional approach is a lot more readable for devs. If you see weird icons in the wrong place it is probably because of a mistake during this transition.

### CODE REVIEW

**Comment by zond** [comment]
Such a huge undertaking! Thanks for taking the time to do this!

It looks good so far, even if there were too many changes for me to look through all. Most of them seemed to be pretty mechanical though, so I guess that's fine.

One thing I noted is that you removed the GitHub workflows, which is fine since they'll need to be replaced with something that deploys a React app instead when we want to deploy - we just need to remember to actually do it :D

**Comment by zond** [comment]
When you feel ready, I'd be happy to merge this into the beta branch so that we get a bit of real testing by our beta users.

**Comment by johnpooch** [comment]
> When you feel ready, I'd be happy to merge this into the beta branch so that we get a bit of real testing by our beta users.

I think we need another week. There are a good few things which just don't work at all atm

**Comment by zond** [comment]
No problem - take your time.

Normally it could be problematic to have this kind of large change hanging, since it would collide with other work, but since the client has been very stable for a long time I don't foresee any conflicting changes happening.

**Comment by zond** [comment]
I got two errors.

The first one was the one I got last time (but was and am still unable to reproduce again), where where the first login POST request gets a 404.

When I reload the page again, I get this error:
image

**Comment by zond** [comment]
Here is a screenshot of the POST 404:
image

How to reproduce:
Go to https://diplicity-engine.appspot.com/, `login`, then `approved-frontends` and delete the one for `localhost:3001`. This will make the server show the `Yes I want to play` dialog again when you try to login the next time.

When the server then POSTs back to the frontend again, I get this error.

**Comment by zond** [comment]
This is now done!

**Pull request closed without merging**
